### ISSUE TITLE
simctl may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [polyhorn/simctl#2]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

Because simctl exposes a safe, unlocked `getenv`, it looks like this wrapper has a data race when `set_env` is called in another thread.

**Comment by cutsoy** [comment]
Hi and thanks for mentioning this. Is your message automated per chance? We don't actually use the 'official' `getenv`. Instead, we call `simctl getenv`, which is a command with (confusingly) the same name that returns an environment variable _within the iOS simulator_. It doesn't use FFI (in fact, it doesn't use any `unsafe` code at all).

Anyway, thanks for pointing me to this!
